using System;
using System.Collections.Generic;
using System.IO;
using LabApi.Events.Handlers;
using LabApi.Features;
using LabApi.Features.Console;
using LabApi.Loader.Features.Plugins;

namespace z5tmsfirstitmesolelyusinglabapi;

public class z5tm : Plugin<configuration>
{
    
    public static z5tm Instance = null!;
    public override void Enable()
    {
        Instance = this;

        InitEvents();
        Logger.Debug("Enabled.");
    }

    public override void Disable()
    {
        Instance = null!;
        Deinitialize();
        Logger.Debug("Disabled.");
    }

    public override string Name { get; } = "z5tmsfirstitmesolelyusinglabapi";
    public override string Description { get; } = "Z5tm's first time solely using LabAPI.";
    public override string Author { get; } = "mt5z";
    public override Version Version { get; } =  new Version(0, 6, 7);
    public override Version RequiredApiVersion { get; } = new (LabApiProperties.CompiledVersion);
    public string[]? FemNames { get; private set; }
    public string[]? MascNames { get; private set; }
    public string[]? LastNames { get; private set; }
    public List<int>? Maxes { get; set; }


    public void InitEvents()
    {
        // if (Instance.Config.EnforceSecurity)
        // {
        //     ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls13; // tls 3, cuz more secure
        //     Logger.Debug("Explicitly permitting solely TLS 1.2 and TLS 1.3.");
        // }
        PlayerEvents.Hurt += AdrenalineRush.Adrenaline; // hello !
        
        
        if (Instance.Config.RPNameOnSpawn)
        {
            PlayerEvents.ChangedRole += RolePlayNameSetter.DoRoleplayNamingShit;
            Logger.Info("Subscribed doroleplayshit to PlayerEvents.Spawned.");
            ServerEvents.WaitingForPlayers += RolePlayNameSetter.RoundStartingShit;
            Logger.Info("Subscribed roundstartingshit to ServerEvents.WaitingForPlayers.");
            // PlayerEvents.Death += roleplaynamesetter.playerdead;
            // Logger.Info("Subscribed playerdead to PlayerEvents.Death.");
            // PlayerEvents.Dying += roleplaynamesetter.SaveNamesOnDeath;
            // Logger.Info("Subscribed savenamesondeath to PlayerEvents.Dying.");
            // Scp049Events.ResurrectedBody += roleplaynamesetter.zombieshit;
        }
        else Logger.Info("Not grabbing RP names. RPNameOnSpawn was false!");
        
        if (!Directory.Exists(Paths.Names))
        {
            Logger.Info($"Creating directory at \"{Paths.Names}\"!");
            Directory.CreateDirectory(Paths.Names); // this is fine because CreateDirectory is recursive !
        } else Logger.Info($"Not creating directory at \"{Paths.Names}\". Already exists.");
        
        var femNamesPath = Path.Combine(Paths.Names, Instance.Config.RPFemFirstNameFileName ?? Defaults.RPFemFirstNameFileName);
        var mascNamesPath = Path.Combine(Paths.Names, Instance.Config.RPMascFirstNameFileName ?? Defaults.RPMascFirstNameFileName);
        var lastNamesPath = Path.Combine(Paths.Names, Instance.Config.RPLastNameFileName ?? Defaults.RPLastNameFileName);
        Logger.Info($"FemNames Path: {femNamesPath} || MascNamesPath: {mascNamesPath} || LastNamesPath: {lastNamesPath}");
        if (File.Exists(femNamesPath))
        {
            try
            {
                FemNames = File.ReadAllLines(femNamesPath);
                Logger.Info("Success on reading feminine names!");
            }
            catch (UnauthorizedAccessException e)
            {
                Logger.Error($"Error when attempting to read file at" + femNamesPath + "!" + e.Message);
            }
            catch (Exception e)
            {
                Logger.Error("Unexpected error when attempting to read file at " + femNamesPath + "!" + e.Message);
            }
        }
        else
        {
            const string splitString = "MARY\nPATRICIA\nLINDA\nBARBARA\nELIZABETH\nJENNIFER\nMARIA\nSUSAN\nMARGARET\nDOROTHY\nLISA\nNANCY\nKAREN\nBETTY\nHELEN\nSANDRA\nDONNA\nCAROL\nRUTH\nSHARON\nMICHELLE\nLAURA\nSARAH\nKIMBERLY\nDEBORAH\nJESSICA\nSHIRLEY\nCYNTHIA\nANGELA\nMELISSA\nBRENDA\nAMY\nANNA\nREBECCA\nVIRGINIA\nKATHLEEN\nPAMELA\nMARTHA\nDEBRA\nAMANDA\nSTEPHANIE\nCAROLYN\nCHRISTINE\nMARIE\nJANET\nCATHERINE\nFRANCES\nANN\nJOYCE\nDIANE\nALICE\nJULIE\nHEATHER\nTERESA\nDORIS\nGLORIA\nEVELYN\nJEAN\nCHERYL\nMILDRED\nKATHERINE\nJOAN\nASHLEY\nJUDITH\nROSE\nJANICE\nKELLY\nNICOLE\nJUDY\nCHRISTINA\nKATHY\nTHERESA\nBEVERLY\nDENISE\nTAMMY\nIRENE\nJANE\nLORI\nRACHEL\nMARILYN\nANDREA\nKATHRYN\nLOUISE\nSARA\nANNE\nJACQUELINE\nWANDA\nBONNIE\nJULIA\nRUBY\nLOIS\nTINA\nPHYLLIS\nNORMA\nPAULA\nDIANA\nANNIE\nLILLIAN\nEMILY\nROBIN\nPEGGY\nCRYSTAL\nGLADYS\nRITA\nDAWN\nCONNIE\nFLORENCE\nTRACY\nEDNA\nTIFFANY\nCARMEN\nROSA\nCINDY\nGRACE\nWENDY\nVICTORIA\nEDITH\nKIM\nSHERRY\nSYLVIA\nJOSEPHINE\nTHELMA\nSHANNON\nSHEILA\nETHEL\nELLEN\nELAINE\nMARJORIE\nCARRIE\nCHARLOTTE\nMONICA\nESTHER\nPAULINE\nEMMA\nJUANITA\nANITA\nRHONDA\nHAZEL\nAMBER\nEVA\nDEBBIE\nAPRIL\nLESLIE\nCLARA\nLUCILLE\nJAMIE\nJOANNE\nELEANOR\nVALERIE\nDANIELLE\nMEGAN\nALICIA\nSUZANNE\nMICHELE\nGAIL\nBERTHA\nDARLENE\nVERONICA\nJILL\nERIN\nGERALDINE\nLAUREN\nCATHY\nJOANN\nLORRAINE\nLYNN\nSALLY\nREGINA\nERICA\nBEATRICE\nDOLORES\nBERNICE\nAUDREY\nYVONNE\nANNETTE\nJUNE\nSAMANTHA\nMARION\nDANA\nSTACY\nANA\nRENEE\nIDA\nVIVIAN\nROBERTA\nHOLLY\nBRITTANY\nMELANIE\nLORETTA\nYOLANDA\nJEANETTE\nLAURIE\nKATIE\nKRISTEN\nVANESSA\nALMA\nSUE\nELSIE\nBETH\nJEANNE\nVICKI\nCARLA\nTARA\nROSEMARY\nEILEEN\nTERRI\nGERTRUDE\nLUCY\nTONYA\nELLA\nSTACEY\nWILMA\nGINA\nKRISTIN\nJESSIE\nNATALIE\nAGNES\nVERA\nWILLIE\nCHARLENE\nBESSIE\nDELORES\nMELINDA\nPEARL\nARLENE\nMAUREEN\nCOLLEEN\nALLISON\nTAMARA\nJOY\nGEORGIA\nCONSTANCE\nLILLIE\nCLAUDIA\nJACKIE\nMARCIA\nTANYA\nNELLIE\nMINNIE\nMARLENE\nHEIDI\nGLENDA\nLYDIA\nVIOLA\nCOURTNEY\nMARIAN\nSTELLA\nCAROLINE\nDORA\nJO\nVICKIE\nMATTIE\nTERRY\nMAXINE\nIRMA\nMABEL\nMARSHA\nMYRTLE\nLENA\nCHRISTY\nDEANNA\nPATSY\nHILDA\nGWENDOLYN\nJENNIE\nNORA\nMARGIE\nNINA\nCASSANDRA\nLEAH\nPENNY\nKAY\nPRISCILLA\nNAOMI\nCAROLE\nBRANDY\nOLGA\nBILLIE\nDIANNE\nTRACEY\nLEONA\nJENNY\nFELICIA\nSONIA\nMIRIAM\nVELMA\nBECKY\nBOBBIE\nVIOLET\nKRISTINA\nTONI\nMISTY\nMAE\nSHELLY\nDAISY\nRAMONA\nSHERRI\nERIKA\nKATRINA\nCLAIRE\nLINDSEY\nLINDSAY\nGENEVA\nGUADALUPE\nBELINDA\nMARGARITA\nSHERYL\nCORA\nFAYE\nADA\nNATASHA\nSABRINA\nISABEL\nMARGUERITE\nHATTIE\nHARRIET\nMOLLY\nCECILIA\nKRISTI\nBRANDI\nBLANCHE\nSANDY\nROSIE\nJOANNA\nIRIS\nEUNICE\nANGIE\nINEZ\nLYNDA\nMADELINE\nAMELIA\nALBERTA\nGENEVIEVE\nMONIQUE\nJODI\nJANIE\nMAGGIE\nKAYLA\nSONYA\nJAN\nLEE\nKRISTINE\nCANDACE\nFANNIE\nMARYANN\nOPAL\nALISON\nYVETTE\nMELODY\nLUZ\nSUSIE\nOLIVIA\nFLORA\nSHELLEY\nKRISTY\nMAMIE\nLULA\nLOLA\nVERNA\nBEULAH\nANTOINETTE\nCANDICE\nJUANA\nJEANNETTE\nPAM\nKELLI\nHANNAH\nWHITNEY\nBRIDGET\nKARLA\nCELIA\nLATOYA\nPATTY\nSHELIA\nGAYLE\nDELLA\nVICKY\nLYNNE\nSHERI\nMARIANNE\nKARA\nJACQUELYN\nERMA\nBLANCA\nMYRA\nLETICIA\nPAT\nKRISTA\nROXANNE\nANGELICA\nJOHNNIE\nROBYN\nFRANCIS\nADRIENNE\nROSALIE\nALEXANDRA\nBROOKE\nBETHANY\nSADIE\nBERNADETTE\nTRACI\nJODY\nKENDRA\nJASMINE\nNICHOLE\nRACHAEL\nCHELSEA\nMABLE\nERNESTINE\nMURIEL\nMARCELLA\nELENA\nKRYSTAL\nANGELINA\nNADINE\nKARI\nESTELLE\nDIANNA\nPAULETTE\nLORA\nMONA\nDOREEN\nROSEMARIE\nANGEL\nDESIREE\nANTONIA\nHOPE\nGINGER\nJANIS\nBETSY\nCHRISTIE\nFREDA\nMERCEDES\nMEREDITH\nLYNETTE\nTERI\nCRISTINA\nEULA\nLEIGH\nMEGHAN\nSOPHIA\nELOISE\nROCHELLE\nGRETCHEN\nCECELIA\nRAQUEL\nHENRIETTA\nALYSSA\nJANA\nKELLEY\nGWEN\nKERRY\nJENNA\nTRICIA\nLAVERNE\nOLIVE\nALEXIS\nTASHA\nSILVIA\nELVIRA\nCASEY\nDELIA\nSOPHIE\nKATE\nPATTI\nLORENA\nKELLIE\nSONJA\nLILA\nLANA\nDARLA\nMAY\nMINDY\nESSIE\nMANDY\nLORENE\nELSA\nJOSEFINA\nJEANNIE\nMIRANDA\nDIXIE\nLUCIA\nMARTA\nFAITH\nLELA\nJOHANNA\nSHARI\nCAMILLE\nTAMI\nSHAWNA\nELISA\nEBONY\nMELBA\nORA\nNETTIE\nTABITHA\nOLLIE\nJAIME\nWINIFRED\nKRISTIE\nMARINA\nALISHA\nAIMEE\nRENA\nMYRNA\nMARLA\nTAMMIE\nLATASHA\nBONITA\nPATRICE\nRONDA\nSHERRIE\nADDIE\nFRANCINE\nDELORIS\nSTACIE\nADRIANA\nCHERI\nSHELBY\nABIGAIL\nCELESTE\nJEWEL\nCARA\nADELE\nREBEKAH\nLUCINDA\nDORTHY\nCHRIS\nEFFIE\nTRINA\nREBA\nSHAWN\nSALLIE\nAURORA\nLENORA\nETTA\nLOTTIE\nKERRI\nTRISHA\nNIKKI\nESTELLA\nFRANCISCA\nJOSIE\nTRACIE\nMARISSA\nKARIN\nBRITTNEY\nJANELLE\nLOURDES\nLAUREL\nHELENE\nFERN\nELVA\nCORINNE\nKELSEY\nINA\nBETTIE\nELISABETH\nAIDA\nCAITLIN\nINGRID\nIVA\nEUGENIA\nCHRISTA\nGOLDIE\nCASSIE\nMAUDE\nJENIFER\nTHERESE\nFRANKIE\nDENA\nLORNA\nJANETTE\nLATONYA\nCANDY\nMORGAN\nCONSUELO\nTAMIKA\nROSETTA\nDEBORA\nCHERIE\nPOLLY\nDINA\nJEWELL\nFAY\nJILLIAN\nDOROTHEA\nNELL\nTRUDY\nESPERANZA\nPATRICA\nKIMBERLEY\nSHANNA\nHELENA\nCAROLINA\nCLEO\nSTEFANIE\nROSARIO\nOLA\nJANINE\nMOLLIE\nLUPE\nALISA\nLOU\nMARIBEL\nSUSANNE\nBETTE\nSUSANA\nELISE\nCECILE\nISABELLE\nLESLEY\nJOCELYN\nPAIGE\nJONI\nRACHELLE\nLEOLA\nDAPHNE\nALTA\nESTER\nPETRA\nGRACIELA\nIMOGENE\nJOLENE\nKEISHA\nLACEY\nGLENNA\nGABRIELA\nKERI\nURSULA\nLIZZIE\nKIRSTEN\nSHANA\nADELINE\nMAYRA\nJAYNE\nJACLYN\nGRACIE\nSONDRA\nCARMELA\nMARISA\nROSALIND\nCHARITY\nTONIA\nBEATRIZ\nMARISOL\nCLARICE\nJEANINE\nSHEENA\nANGELINE\nFRIEDA\nLILY\nROBBIE\nSHAUNA\nMILLIE\nCLAUDETTE\nCATHLEEN\nANGELIA\nGABRIELLE\nAUTUMN\nKATHARINE\nSUMMER\nJODIE\nSTACI\nLEA\nCHRISTI\nJIMMIE\nJUSTINE\nELMA\nLUELLA\nMARGRET\nDOMINIQUE\nSOCORRO\nRENE\nMARTINA\nMARGO\nMAVIS\nCALLIE\nBOBBI\nMARITZA\nLUCILE\nLEANNE\nJEANNINE\nDEANA\nAILEEN\nLORIE\nLADONNA\nWILLA\nMANUELA\nGALE\nSELMA\nDOLLY\nSYBIL\nABBY\nLARA\nDALE\nIVY\nDEE\nWINNIE\nMARCY\nLUISA\nJERI\nMAGDALENA\nOFELIA\nMEAGAN\nAUDRA\nMATILDA\nLEILA\nCORNELIA\nBIANCA\nSIMONE\nBETTYE\nRANDI\nVIRGIE\nLATISHA\nBARBRA\nGEORGINA\nELIZA\nLEANN\nBRIDGETTE\nRHODA\nHALEY\nADELA\nNOLA\nBERNADINE\nFLOSSIE\nILA\nGRETA\nRUTHIE\nNELDA\nMINERVA\nLILLY\nTERRIE\nLETHA\nHILARY\nESTELA\nVALARIE\nBRIANNA\nROSALYN\nEARLINE\nCATALINA\nAVA\nMIA\nCLARISSA\nLIDIA\nCORRINE\nALEXANDRIA\nCONCEPCION\nTIA\nSHARRON\nRAE\nDONA\nERICKA\nJAMI\nELNORA\nCHANDRA\nLENORE\nNEVA\nMARYLOU\nMELISA\nTABATHA\nSERENA\nAVIS\nALLIE\nSOFIA\nJEANIE\nODESSA\nNANNIE\nHARRIETT\nLORAINE\nPENELOPE\nMILAGROS\nEMILIA\nBENITA\nALLYSON\nASHLEE\nTANIA\nTOMMIE\nESMERALDA\nKARINA\nEVE\nPEARLIE\nZELMA\nMALINDA\nNOREEN\nTAMEKA\nSAUNDRA\nHILLARY\nAMIE\nALTHEA\nROSALINDA\nJORDAN\nLILIA\nALANA\nGAY\nCLARE\nALEJANDRA\nELINOR\nMICHAEL\nLORRIE\nJERRI\nDARCY\nEARNESTINE\nCARMELLA\nTAYLOR\nNOEMI\nMARCIE\nLIZA\nANNABELLE\nLOUISA\nEARLENE\nMALLORY\nCARLENE\nNITA\nSELENA\nTANISHA\nKATY\nJULIANNE\nJOHN\nLAKISHA\nEDWINA\nMARICELA\nMARGERY\nKENYA\nDOLLIE\nROXIE\nROSLYN\nKATHRINE\nNANETTE\nCHARMAINE\nLAVONNE\nILENE\nKRIS\nTAMMI\nSUZETTE\nCORINE\nKAYE\nJERRY\nMERLE\nCHRYSTAL\nLINA\nDEANNE\nLILIAN\nJULIANA\nALINE\nLUANN\nKASEY\nMARYANNE\nEVANGELINE\nCOLETTE\nMELVA\nLAWANDA\nYESENIA\nNADIA\nMADGE\nKATHIE\nEDDIE\nOPHELIA\nVALERIA\nNONA\nMITZI\nMARI\nGEORGETTE\nCLAUDINE\nFRAN\nALISSA\nROSEANN\nLAKEISHA\nSUSANNA\nREVA\nDEIDRE\nCHASITY\nSHEREE\nCARLY\nJAMES\nELVIA\nALYCE\nDEIRDRE\nGENA\nBRIANA\nARACELI\nKATELYN\nROSANNE\nWENDI\nTESSA\nBERTA\nMARVA\nIMELDA\nMARIETTA\nMARCI\nLEONOR\nARLINE\nSASHA\nMADELYN\nJANNA\nJULIETTE\nDEENA\nAURELIA\nJOSEFA\nAUGUSTA\nLILIANA\nYOUNG\nCHRISTIAN\nLESSIE\nAMALIA\nSAVANNAH\nANASTASIA\nVILMA\nNATALIA\nROSELLA\nLYNNETTE\nCORINA\nALFREDA\nLEANNA\nCAREY\nAMPARO\nCOLEEN\nTAMRA\nAISHA\nWILDA\nKARYN\nCHERRY\nQUEEN\nMAURA\nMAI\nEVANGELINA\nROSANNA\nHALLIE\nERNA\nENID\nMARIANA\nLACY\nJULIET\nJACKLYN\nFREIDA\nMADELEINE\nMARA\nHESTER\nCATHRYN\nLELIA\nCASANDRA\nBRIDGETT\nANGELITA\nJANNIE\nDIONNE\nANNMARIE\nKATINA\nBERYL\nPHOEBE\nMILLICENT\nKATHERYN\nDIANN\nCARISSA\nMARYELLEN\nLIZ\nLAURI\nHELGA\nGILDA\nADRIAN\nRHEA\nMARQUITA\nHOLLIE\nTISHA\nTAMERA\nANGELIQUE\nFRANCESCA\nBRITNEY\nKAITLIN\nLOLITA\nFLORINE\nROWENA\nREYNA\nTWILA\nFANNY\nJANELL\nINES\nCONCETTA\nBERTIE\nALBA\nBRIGITTE\nALYSON\nVONDA\nPANSY\nELBA\nNOELLE\nLETITIA\nKITTY\nDEANN\nBRANDIE\nLOUELLA\nLETA\nFELECIA\nSHARLENE\nLESA\nBEVERLEY\nROBERT\nISABELLA\nHERMINIA\nTERRA\nCELINA";
            FemNames = splitString.Split('\n');
            Logger.Info($"File at {femNamesPath} does NOT exist. Falling back to biggie cheese fem names...");
        }
        if (File.Exists(mascNamesPath))
        {
            try
            {
                MascNames = File.ReadAllLines(mascNamesPath);
                Logger.Info("Success on reading masc names!");
            }
            catch (UnauthorizedAccessException e)
            {
                Logger.Error($"Error when attempting to read file at" + mascNamesPath + "!" + e.Message);
            }
            catch (Exception e)
            {
                Logger.Error("Unexpected error when attempting to read file at " + mascNamesPath + "!" + e.Message);
            }
        }
        else
        {
            const string splitString = "JAMES\nJOHN\nROBERT\nMICHAEL\nWILLIAM\nDAVID\nRICHARD\nCHARLES\nJOSEPH\nTHOMAS\nCHRISTOPHER\nDANIEL\nPAUL\nMARK\nDONALD\nGEORGE\nKENNETH\nSTEVEN\nEDWARD\nBRIAN\nRONALD\nANTHONY\nKEVIN\nJASON\nMATTHEW\nGARY\nTIMOTHY\nJOSE\nLARRY\nJEFFREY\nFRANK\nSCOTT\nERIC\nSTEPHEN\nANDREW\nRAYMOND\nGREGORY\nJOSHUA\nJERRY\nDENNIS\nWALTER\nPATRICK\nPETER\nHAROLD\nDOUGLAS\nHENRY\nCARL\nARTHUR\nRYAN\nROGER\nJOE\nJUAN\nJACK\nALBERT\nJONATHAN\nJUSTIN\nTERRY\nGERALD\nKEITH\nSAMUEL\nWILLIE\nRALPH\nLAWRENCE\nNICHOLAS\nROY\nBENJAMIN\nBRUCE\nBRANDON\nADAM\nHARRY\nFRED\nWAYNE\nBILLY\nSTEVE\nLOUIS\nJEREMY\nAARON\nRANDY\nHOWARD\nEUGENE\nCARLOS\nRUSSELL\nBOBBY\nVICTOR\nMARTIN\nERNEST\nPHILLIP\nTODD\nJESSE\nCRAIG\nALAN\nSHAWN\nCLARENCE\nSEAN\nPHILIP\nCHRIS\nJOHNNY\nEARL\nJIMMY\nANTONIO\nDANNY\nBRYAN\nTONY\nLUIS\nMIKE\nSTANLEY\nLEONARD\nNATHAN\nDALE\nMANUEL\nRODNEY\nCURTIS\nNORMAN\nALLEN\nMARVIN\nVINCENT\nGLENN\nJEFFERY\nTRAVIS\nJEFF\nCHAD\nJACOB\nLEE\nMELVIN\nALFRED\nKYLE\nFRANCIS\nBRADLEY\nJESUS\nHERBERT\nFREDERICK\nRAY\nJOEL\nEDWIN\nDON\nEDDIE\nRICKY\nTROY\nRANDALL\nBARRY\nALEXANDER\nBERNARD\nMARIO\nLEROY\nFRANCISCO\nMARCUS\nMICHEAL\nTHEODORE\nCLIFFORD\nMIGUEL\nOSCAR\nJAY\nJIM\nTOM\nCALVIN\nALEX\nJON\nRONNIE\nBILL\nLLOYD\nTOMMY\nLEON\nDEREK\nWARREN\nDARRELL\nJEROME\nFLOYD\nLEO\nALVIN\nTIM\nWESLEY\nGORDON\nDEAN\nGREG\nJORGE\nDUSTIN\nPEDRO\nDERRICK\nDAN\nLEWIS\nZACHARY\nCOREY\nHERMAN\nMAURICE\nVERNON\nROBERTO\nCLYDE\nGLEN\nHECTOR\nSHANE\nRICARDO\nSAM\nRICK\nLESTER\nBRENT\nRAMON\nCHARLIE\nTYLER\nGILBERT\nGENE\nMARC\nREGINALD\nRUBEN\nBRETT\nANGEL\nNATHANIEL\nRAFAEL\nLESLIE\nEDGAR\nMILTON\nRAUL\nBEN\nCHESTER\nCECIL\nDUANE\nFRANKLIN\nANDRE\nELMER\nBRAD\nGABRIEL\nRON\nMITCHELL\nROLAND\nARNOLD\nHARVEY\nJARED\nADRIAN\nKARL\nCORY\nCLAUDE\nERIK\nDARRYL\nJAMIE\nNEIL\nJESSIE\nCHRISTIAN\nJAVIER\nFERNANDO\nCLINTON\nTED\nMATHEW\nTYRONE\nDARREN\nLONNIE\nLANCE\nCODY\nJULIO\nKELLY\nKURT\nALLAN\nNELSON\nGUY\nCLAYTON\nHUGH\nMAX\nDWAYNE\nDWIGHT\nARMANDO\nFELIX\nJIMMIE\nEVERETT\nJORDAN\nIAN\nWALLACE\nKEN\nBOB\nJAIME\nCASEY\nALFREDO\nALBERTO\nDAVE\nIVAN\nJOHNNIE\nSIDNEY\nBYRON\nJULIAN\nISAAC\nMORRIS\nCLIFTON\nWILLARD\nDARYL\nROSS\nVIRGIL\nANDY\nMARSHALL\nSALVADOR\nPERRY\nKIRK\nSERGIO\nMARION\nTRACY\nSETH\nKENT\nTERRANCE\nRENE\nEDUARDO\nTERRENCE\nENRIQUE\nFREDDIE\nWADE\nAUSTIN\nSTUART\nFREDRICK\nARTURO\nALEJANDRO\nJACKIE\nJOEY\nNICK\nLUTHER\nWENDELL\nJEREMIAH\nEVAN\nJULIUS\nDANA\nDONNIE\nOTIS\nSHANNON\nTREVOR\nOLIVER\nLUKE\nHOMER\nGERARD\nDOUG\nKENNY\nHUBERT\nANGELO\nSHAUN\nLYLE\nMATT\nLYNN\nALFONSO\nORLANDO\nREX\nCARLTON\nERNESTO\nCAMERON\nNEAL\nPABLO\nLORENZO\nOMAR\nWILBUR\nBLAKE\nGRANT\nHORACE\nRODERICK\nKERRY\nABRAHAM\nWILLIS\nRICKEY\nJEAN\nIRA\nANDRES\nCESAR\nJOHNATHAN\nMALCOLM\nRUDOLPH\nDAMON\nKELVIN\nRUDY\nPRESTON\nALTON\nARCHIE\nMARCO\nWM\nPETE\nRANDOLPH\nGARRY\nGEOFFREY\nJONATHON\nFELIPE\nBENNIE\nGERARDO\nED\nDOMINIC\nROBIN\nLOREN\nDELBERT\nCOLIN\nGUILLERMO\nEARNEST\nLUCAS\nBENNY\nNOEL\nSPENCER\nRODOLFO\nMYRON\nEDMUND\nGARRETT\nSALVATORE\nCEDRIC\nLOWELL\nGREGG\nSHERMAN\nWILSON\nDEVIN\nSYLVESTER\nKIM\nROOSEVELT\nISRAEL\nJERMAINE\nFORREST\nWILBERT\nLELAND\nSIMON\nGUADALUPE\nCLARK\nIRVING\nCARROLL\nBRYANT\nOWEN\nRUFUS\nWOODROW\nSAMMY\nKRISTOPHER\nMACK\nLEVI\nMARCOS\nGUSTAVO\nJAKE\nLIONEL\nMARTY\nTAYLOR\nELLIS\nDALLAS\nGILBERTO\nCLINT\nNICOLAS\nLAURENCE\nISMAEL\nORVILLE\nDREW\nJODY\nERVIN\nDEWEY\nAL\nWILFRED\nJOSH\nHUGO\nIGNACIO\nCALEB\nTOMAS\nSHELDON\nERICK\nFRANKIE\nSTEWART\nDOYLE\nDARREL\nROGELIO\nTERENCE\nSANTIAGO\nALONZO\nELIAS\nBERT\nELBERT\nRAMIRO\nCONRAD\nPAT\nNOAH\nGRADY\nPHIL\nCORNELIUS\nLAMAR\nROLANDO\nCLAY\nPERCY\nDEXTER\nBRADFORD\nMERLE\nDARIN\nAMOS\nTERRELL\nMOSES\nIRVIN\nSAUL\nROMAN\nDARNELL\nRANDAL\nTOMMIE\nTIMMY\nDARRIN\nWINSTON\nBRENDAN\nTOBY\nVAN\nABEL\nDOMINICK\nBOYD\nCOURTNEY\nJAN\nEMILIO\nELIJAH\nCARY\nDOMINGO\nSANTOS\nAUBREY\nEMMETT\nMARLON\nEMANUEL\nJERALD\nEDMOND\nEMIL\nDEWAYNE\nWILL\nOTTO\nTEDDY\nREYNALDO\nBRET\nMORGAN\nJESS\nTRENT\nHUMBERTO\nEMMANUEL\nSTEPHAN\nLOUIE\nVICENTE\nLAMONT\nSTACY\nGARLAND\nMILES\nMICAH\nEFRAIN\nBILLIE\nLOGAN\nHEATH\nRODGER\nHARLEY\nDEMETRIUS\nETHAN\nELDON\nROCKY\nPIERRE\nJUNIOR\nFREDDY\nELI\nBRYCE\nANTOINE\nROBBIE\nKENDALL\nROYCE\nSTERLING\nMICKEY\nCHASE\nGROVER\nELTON\nCLEVELAND\nDYLAN\nCHUCK\nDAMIAN\nREUBEN\nSTAN\nAUGUST\nLEONARDO\nJASPER\nRUSSEL\nERWIN\nBENITO\nHANS\nMONTE\nBLAINE\nERNIE\nCURT\nQUENTIN\nAGUSTIN\nMURRAY\nJAMAL\nDEVON\nADOLFO\nHARRISON\nTYSON\nBURTON\nBRADY\nELLIOTT\nWILFREDO\nBART\nJARROD\nVANCE\nDENIS\nDAMIEN\nJOAQUIN\nHARLAN\nDESMOND\nELLIOT\nDARWIN\nASHLEY\nGREGORIO\nBUDDY\nXAVIER\nKERMIT\nROSCOE\nESTEBAN\nANTON\nSOLOMON\nSCOTTY\nNORBERT\nELVIN\nWILLIAMS\nNOLAN\nCAREY\nROD\nQUINTON\nHAL\nBRAIN\nROB\nELWOOD\nKENDRICK\nDARIUS\nMOISES\nSON\nMARLIN\nFIDEL\nTHADDEUS\nCLIFF\nMARCEL\nALI\nJACKSON\nRAPHAEL\nBRYON\nARMAND\nALVARO\nJEFFRY\nDANE\nJOESPH\nTHURMAN\nNED\nSAMMIE\nRUSTY\nMICHEL\nMONTY\nRORY\nFABIAN\nREGGIE\nMASON\nGRAHAM\nKRIS\nISAIAH\nVAUGHN\nGUS\nAVERY\nLOYD\nDIEGO\nALEXIS\nADOLPH\nNORRIS\nMILLARD\nROCCO\nGONZALO\nDERICK\nRODRIGO\nGERRY\nSTACEY\nCARMEN\nWILEY\nRIGOBERTO\nALPHONSO\nTY\nSHELBY\nRICKIE\nNOE\nVERN\nBOBBIE\nREED\nJEFFERSON\nELVIS\nBERNARDO\nMAURICIO\nHIRAM\nDONOVAN\nBASIL\nRILEY\nOLLIE\nNICKOLAS\nMAYNARD\nSCOT\nVINCE\nQUINCY\nEDDY\nSEBASTIAN\nFEDERICO\nULYSSES\nHERIBERTO\nDONNELL\nCOLE\nDENNY\nDAVIS\nGAVIN\nEMERY\nWARD\nROMEO\nJAYSON\nDION\nDANTE\nCLEMENT\nCOY\nODELL\nMAXWELL\nJARVIS\nBRUNO\nISSAC\nMARY\nDUDLEY\nBROCK\nSANFORD\nCOLBY\nCARMELO\nBARNEY\nNESTOR\nHOLLIS\nSTEFAN\nDONNY\nART\nLINWOOD\nBEAU\nWELDON\nGALEN\nISIDRO\nTRUMAN\nDELMAR\nJOHNATHON\nSILAS\nFREDERIC\nDICK\nKIRBY\nIRWIN\nCRUZ\nMERLIN\nMERRILL\nCHARLEY\nMARCELINO\nLANE\nHARRIS\nCLEO\nCARLO\nTRENTON\nKURTIS\nHUNTER\nAURELIO\nWINFRED\nVITO\nCOLLIN\nDENVER\nCARTER\nLEONEL\nEMORY\nPASQUALE\nMOHAMMAD\nMARIANO\nDANIAL\nBLAIR\nLANDON\nDIRK\nBRANDEN\nADAN\nNUMBERS\nCLAIR\nBUFORD\nGERMAN\nBERNIE\nWILMER\nJOAN\nEMERSON\nZACHERY\nFLETCHER\nJACQUES\nERROL\nDALTON\nMONROE\nJOSUE\nDOMINIQUE\nEDWARDO\nBOOKER\nWILFORD\nSONNY\nSHELTON\nCARSON\nTHERON\nRAYMUNDO\nDAREN\nTRISTAN\nHOUSTON\nROBBY\nLINCOLN\nJAME\nGENARO\nGALE\nBENNETT\nOCTAVIO\nCORNELL\nLAVERNE\nHUNG\nARRON\nANTONY\nHERSCHEL\nALVA\nGIOVANNI\nGARTH\nCYRUS\nCYRIL\nRONNY\nSTEVIE\nLON\nFREEMAN\nERIN\nDUNCAN\nKENNITH\nCARMINE\nAUGUSTINE\nYOUNG\nERICH\nCHADWICK\nWILBURN\nRUSS\nREID\nMYLES\nANDERSON\nMORTON\nJONAS\nFOREST\nMITCHEL\nMERVIN\nZANE\nRICH\nJAMEL\nLAZARO\nALPHONSE\nRANDELL\nMAJOR\nJOHNIE\nJARRETT\nBROOKS\nARIEL\nABDUL\nDUSTY\nLUCIANO\nLINDSEY\nTRACEY\nSEYMOUR\nSCOTTIE\nEUGENIO\nMOHAMMED\nSANDY\nVALENTIN\nCHANCE\nARNULFO\nLUCIEN\nFERDINAND\nTHAD\nEZRA\nSYDNEY\nALDO\nRUBIN\nROYAL\nMITCH\nEARLE\nABE\nWYATT\nMARQUIS\nLANNY\nKAREEM\nJAMAR\nBORIS\nISIAH\nEMILE\nELMO\nARON\nLEOPOLDO\nEVERETTE\nJOSEF\nGAIL\nELOY\nDORIAN\nRODRICK\nREINALDO\nLUCIO\nJERROD\nWESTON\nHERSHEL\nBARTON\nPARKER\nLEMUEL\nLAVERN\nBURT\nJULES\nGIL\nELISEO\nAHMAD\nNIGEL\nEFREN\nANTWAN\nALDEN\nMARGARITO\nCOLEMAN\nREFUGIO\nDINO\nOSVALDO\nLES\nDEANDRE\nNORMAND\nKIETH\nIVORY\nANDREA\nTREY\nNORBERTO\nNAPOLEON\nJEROLD\nFRITZ\nROSENDO\nMILFORD\nSANG\nDEON\nCHRISTOPER\nALFONZO\nLYMAN\nJOSIAH\nBRANT\nWILTON\nRICO\nJAMAAL\nDEWITT\nCAROL\nBRENTON\nYONG\nOLIN\nFOSTER\nFAUSTINO\nCLAUDIO\nJUDSON\nGINO\nEDGARDO\nBERRY\nALEC\nTANNER\nJARRED\nDONN\nTRINIDAD\nTAD\nSHIRLEY\nPRINCE\nPORFIRIO\nODIS\nMARIA\nLENARD\nCHAUNCEY\nCHANG\nTOD\nMEL\nMARCELO\nKORY\nAUGUSTUS\nKEVEN\nHILARIO\nBUD\nSAL\nROSARIO\nORVAL\nMAURO\nDANNIE\nZACHARIAH\nOLEN\nANIBAL\nMILO\nJED\nFRANCES\nTHANH\nDILLON\nAMADO\nNEWTON\nCONNIE\nLENNY\nTORY\nRICHIE\nLUPE\nHORACIO\nBRICE\nMOHAMED\nDELMER\nDARIO\nREYES\nDEE\nMAC\nJONAH\nJERROLD\nROBT\nHANK\nSUNG\nRUPERT\nROLLAND\nKENTON\nDAMION\nCHI\nANTONE\nWALDO\nFREDRIC\nBRADLY\nQUINN\nKIP\nBURL\nWALKER\nTYREE\nJEFFEREY\nAHMED\nBIGGIE";
            MascNames = splitString.Split('\n');
            Logger.Info($"File at {mascNamesPath} does NOT exist. Falling back to biggie cheese masc names...");
        }
        if (File.Exists(lastNamesPath))
        {
            try
            {
                LastNames = File.ReadAllLines(lastNamesPath);
                Logger.Info("Success on reading last names!");
            }
            catch (UnauthorizedAccessException e)
            {
                Logger.Error($"Error when attempting to read file at" + lastNamesPath + "!" + e.Message);
            }
            catch (Exception e)
            {
                Logger.Error("Unexpected error when attempting to read file at " + lastNamesPath + "!" + e.Message);
            }
        }
        else
        {
            const string splitString = "SMITH\nJOHNSON\nWILLIAMS\nJONES\nBROWN\nDAVIS\nMILLER\nWILSON\nMOORE\nTAYLOR\nANDERSON\nTHOMAS\nJACKSON\nWHITE\nHARRIS\nMARTIN\nTHOMPSON\nGARCIA\nMARTINEZ\nROBINSON\nCLARK\nRODRIGUEZ\nLEWIS\nLEE\nWALKER\nHALL\nALLEN\nYOUNG\nHERNANDEZ\nKING\nWRIGHT\nLOPEZ\nHILL\nSCOTT\nGREEN\nADAMS\nBAKER\nGONZALEZ\nNELSON\nCARTER\nMITCHELL\nPEREZ\nROBERTS\nTURNER\nPHILLIPS\nCAMPBELL\nPARKER\nEVANS\nEDWARDS\nCOLLINS\nSTEWART\nSANCHEZ\nMORRIS\nROGERS\nREED\nCOOK\nMORGAN\nBELL\nMURPHY\nBAILEY\nRIVERA\nCOOPER\nRICHARDSON\nCOX\nHOWARD\nWARD\nTORRES\nPETERSON\nGRAY\nRAMIREZ\nJAMES\nWATSON\nBROOKS\nKELLY\nSANDERS\nPRICE\nBENNETT\nWOOD\nBARNES\nROSS\nHENDERSON\nCOLEMAN\nJENKINS\nPERRY\nPOWELL\nLONG\nPATTERSON\nHUGHES\nFLORES\nWASHINGTON\nBUTLER\nSIMMONS\nFOSTER\nGONZALES\nBRYANT\nALEXANDER\nRUSSELL\nGRIFFIN\nDIAZ\nHAYES\nMYERS\nFORD\nHAMILTON\nGRAHAM\nSULLIVAN\nWALLACE\nWOODS\nCOLE\nWEST\nJORDAN\nOWENS\nREYNOLDS\nFISHER\nELLIS\nHARRISON\nGIBSON\nMCDONALD\nCRUZ\nMARSHALL\nORTIZ\nGOMEZ\nMURRAY\nFREEMAN\nWELLS\nWEBB\nSIMPSON\nSTEVENS\nTUCKER\nPORTER\nHUNTER\nHICKS\nCRAWFORD\nHENRY\nBOYD\nMASON\nMORALES\nKENNEDY\nWARREN\nDIXON\nRAMOS\nREYES\nBURNS\nGORDON\nSHAW\nHOLMES\nRICE\nROBERTSON\nHUNT\nBLACK\nDANIELS\nPALMER\nMILLS\nNICHOLS\nGRANT\nKNIGHT\nFERGUSON\nROSE\nSTONE\nHAWKINS\nDUNN\nPERKINS\nHUDSON\nSPENCER\nGARDNER\nSTEPHENS\nPAYNE\nPIERCE\nBERRY\nMATTHEWS\nARNOLD\nWAGNER\nWILLIS\nRAY\nWATKINS\nOLSON\nCARROLL\nDUNCAN\nSNYDER\nHART\nCUNNINGHAM\nBRADLEY\nLANE\nANDREWS\nRUIZ\nHARPER\nFOX\nRILEY\nARMSTRONG\nCARPENTER\nWEAVER\nGREENE\nLAWRENCE\nELLIOTT\nCHAVEZ\nSIMS\nAUSTIN\nPETERS\nKELLEY\nFRANKLIN\nLAWSON\nFIELDS\nGUTIERREZ\nRYAN\nSCHMIDT\nCARR\nVASQUEZ\nCASTILLO\nWHEELER\nCHAPMAN\nOLIVER\nMONTGOMERY\nRICHARDS\nWILLIAMSON\nJOHNSTON\nBANKS\nMEYER\nBISHOP\nMCCOY\nHOWELL\nALVAREZ\nMORRISON\nHANSEN\nFERNANDEZ\nGARZA\nHARVEY\nLITTLE\nBURTON\nSTANLEY\nNGUYEN\nGEORGE\nJACOBS\nREID\nKIM\nFULLER\nLYNCH\nDEAN\nGILBERT\nGARRETT\nROMERO\nWELCH\nLARSON\nFRAZIER\nBURKE\nHANSON\nDAY\nMENDOZA\nMORENO\nBOWMAN\nMEDINA\nFOWLER\nBREWER\nHOFFMAN\nCARLSON\nSILVA\nPEARSON\nHOLLAND\nDOUGLAS\nFLEMING\nJENSEN\nVARGAS\nBYRD\nDAVIDSON\nHOPKINS\nMAY\nTERRY\nHERRERA\nWADE\nSOTO\nWALTERS\nCURTIS\nNEAL\nCALDWELL\nLOWE\nJENNINGS\nBARNETT\nGRAVES\nJIMENEZ\nHORTON\nSHELTON\nBARRETT\nOBRIEN\nCASTRO\nSUTTON\nGREGORY\nMCKINNEY\nLUCAS\nMILES\nCRAIG\nRODRIQUEZ\nCHAMBERS\nHOLT\nLAMBERT\nFLETCHER\nWATTS\nBATES\nHALE\nRHODES\nPENA\nBECK\nNEWMAN\nHAYNES\nMCDANIEL\nMENDEZ\nBUSH\nVAUGHN\nPARKS\nDAWSON\nSANTIAGO\nNORRIS\nHARDY\nLOVE\nSTEELE\nCURRY\nPOWERS\nSCHULTZ\nBARKER\nGUZMAN\nPAGE\nMUNOZ\nBALL\nKELLER\nCHANDLER\nWEBER\nLEONARD\nWALSH\nLYONS\nRAMSEY\nWOLFE\nSCHNEIDER\nMULLINS\nBENSON\nSHARP\nBOWEN\nDANIEL\nBARBER\nCUMMINGS\nHINES\nBALDWIN\nGRIFFITH\nVALDEZ\nHUBBARD\nSALAZAR\nREEVES\nWARNER\nSTEVENSON\nBURGESS\nSANTOS\nTATE\nCROSS\nGARNER\nMANN\nMACK\nMOSS\nTHORNTON\nDENNIS\nMCGEE\nFARMER\nDELGADO\nAGUILAR\nVEGA\nGLOVER\nMANNING\nCOHEN\nHARMON\nRODGERS\nROBBINS\nNEWTON\nTODD\nBLAIR\nHIGGINS\nINGRAM\nREESE\nCANNON\nSTRICKLAND\nTOWNSEND\nPOTTER\nGOODWIN\nWALTON\nROWE\nHAMPTON\nORTEGA\nPATTON\nSWANSON\nJOSEPH\nFRANCIS\nGOODMAN\nMALDONADO\nYATES\nBECKER\nERICKSON\nHODGES\nRIOS\nCONNER\nADKINS\nWEBSTER\nNORMAN\nMALONE\nHAMMOND\nFLOWERS\nCOBB\nMOODY\nQUINN\nBLAKE\nMAXWELL\nPOPE\nFLOYD\nOSBORNE\nPAUL\nMCCARTHY\nGUERRERO\nLINDSEY\nESTRADA\nSANDOVAL\nGIBBS\nTYLER\nGROSS\nFITZGERALD\nSTOKES\nDOYLE\nSHERMAN\nSAUNDERS\nWISE\nCOLON\nGILL\nALVARADO\nGREER\nPADILLA\nSIMON\nWATERS\nNUNEZ\nBALLARD\nSCHWARTZ\nMCBRIDE\nHOUSTON\nCHRISTENSEN\nKLEIN\nPRATT\nBRIGGS\nPARSONS\nMCLAUGHLIN\nZIMMERMAN\nFRENCH\nBUCHANAN\nMORAN\nCOPELAND\nROY\nPITTMAN\nBRADY\nMCCORMICK\nHOLLOWAY\nBROCK\nPOOLE\nFRANK\nLOGAN\nOWEN\nBASS\nMARSH\nDRAKE\nWONG\nJEFFERSON\nPARK\nMORTON\nABBOTT\nSPARKS\nPATRICK\nNORTON\nHUFF\nCLAYTON\nMASSEY\nLLOYD\nFIGUEROA\nCARSON\nBOWERS\nROBERSON\nBARTON\nTRAN\nLAMB\nHARRINGTON\nCASEY\nBOONE\nCORTEZ\nCLARKE\nMATHIS\nSINGLETON\nWILKINS\nCAIN\nBRYAN\nUNDERWOOD\nHOGAN\nMCKENZIE\nCOLLIER\nLUNA\nPHELPS\nMCGUIRE\nALLISON\nBRIDGES\nWILKERSON\nNASH\nSUMMERS\nATKINS\nWILCOX\nPITTS\nCONLEY\nMARQUEZ\nBURNETT\nRICHARD\nCOCHRAN\nCHASE\nDAVENPORT\nHOOD\nGATES\nCLAY\nAYALA\nSAWYER\nROMAN\nVAZQUEZ\nDICKERSON\nHODGE\nACOSTA\nFLYNN\nESPINOZA\nNICHOLSON\nMONROE\nWOLF\nMORROW\nKIRK\nRANDALL\nANTHONY\nWHITAKER\nOCONNOR\nSKINNER\nWARE\nMOLINA\nKIRBY\nHUFFMAN\nBRADFORD\nCHARLES\nGILMORE\nDOMINGUEZ\nONEAL\nBRUCE\nLANG\nCOMBS\nKRAMER\nHEATH\nHANCOCK\nGALLAGHER\nGAINES\nSHAFFER\nSHORT\nWIGGINS\nMATHEWS\nMCCLAIN\nFISCHER\nWALL\nSMALL\nMELTON\nHENSLEY\nBOND\nDYER\nCAMERON\nGRIMES\nCONTRERAS\nCHRISTIAN\nWYATT\nBAXTER\nSNOW\nMOSLEY\nSHEPHERD\nLARSEN\nHOOVER\nBEASLEY\nGLENN\nPETERSEN\nWHITEHEAD\nMEYERS\nKEITH\nGARRISON\nVINCENT\nSHIELDS\nHORN\nSAVAGE\nOLSEN\nSCHROEDER\nHARTMAN\nWOODARD\nMUELLER\nKEMP\nDELEON\nBOOTH\nPATEL\nCALHOUN\nWILEY\nEATON\nCLINE\nNAVARRO\nHARRELL\nLESTER\nHUMPHREY\nPARRISH\nDURAN\nHUTCHINSON\nHESS\nDORSEY\nBULLOCK\nROBLES\nBEARD\nDALTON\nAVILA\nVANCE\nRICH\nBLACKWELL\nYORK\nJOHNS\nBLANKENSHIP\nTREVINO\nSALINAS\nCAMPOS\nPRUITT\nMOSES\nCALLAHAN\nGOLDEN\nMONTOYA\nHARDIN\nGUERRA\nMCDOWELL\nCAREY\nSTAFFORD\nGALLEGOS\nHENSON\nWILKINSON\nBOOKER\nMERRITT\nMIRANDA\nATKINSON\nORR\nDECKER\nHOBBS\nPRESTON\nTANNER\nKNOX\nPACHECO\nSTEPHENSON\nGLASS\nROJAS\nSERRANO\nMARKS\nHICKMAN\nENGLISH\nSWEENEY\nSTRONG\nPRINCE\nMCCLURE\nCONWAY\nWALTER\nROTH\nMAYNARD\nFARRELL\nLOWERY\nHURST\nNIXON\nWEISS\nTRUJILLO\nELLISON\nSLOAN\nJUAREZ\nWINTERS\nMCLEAN\nRANDOLPH\nLEON\nBOYER\nVILLARREAL\nMCCALL\nGENTRY\nCARRILLO\nKENT\nAYERS\nLARA\nSHANNON\nSEXTON\nPACE\nHULL\nLEBLANC\nBROWNING\nVELASQUEZ\nLEACH\nCHANG\nHOUSE\nSELLERS\nHERRING\nNOBLE\nFOLEY\nBARTLETT\nMERCADO\nLANDRY\nDURHAM\nWALLS\nBARR\nMCKEE\nBAUER\nRIVERS\nEVERETT\nBRADSHAW\nPUGH\nVELEZ\nRUSH\nESTES\nDODSON\nMORSE\nSHEPPARD\nWEEKS\nCAMACHO\nBEAN\nBARRON\nLIVINGSTON\nMIDDLETON\nSPEARS\nBRANCH\nBLEVINS\nCHEN\nKERR\nMCCONNELL\nHATFIELD\nHARDING\nASHLEY\nSOLIS\nHERMAN\nFROST\nGILES\nBLACKBURN\nWILLIAM\nPENNINGTON\nWOODWARD\nFINLEY\nMCINTOSH\nKOCH\nBEST\nSOLOMON\nMCCULLOUGH\nDUDLEY\nNOLAN\nBLANCHARD\nRIVAS\nBRENNAN\nMEJIA\nKANE\nBENTON\nJOYCE\nBUCKLEY\nHALEY\nVALENTINE\nMADDOX\nRUSSO\nMCKNIGHT\nBUCK\nMOON\nMCMILLAN\nCROSBY\nBERG\nDOTSON\nMAYS\nROACH\nCHURCH\nCHAN\nRICHMOND\nMEADOWS\nFAULKNER\nONEILL\nKNAPP\nKLINE\nBARRY\nOCHOA\nJACOBSON\nGAY\nAVERY\nHENDRICKS\nHORNE\nSHEPARD\nHEBERT\nCHERRY\nCARDENAS\nMCINTYRE\nWHITNEY\nWALLER\nHOLMAN\nDONALDSON\nCANTU\nTERRELL\nMORIN\nGILLESPIE\nFUENTES\nTILLMAN\nSANFORD\nBENTLEY\nPECK\nKEY\nSALAS\nROLLINS\nGAMBLE\nDICKSON\nBATTLE\nSANTANA\nCABRERA\nCERVANTES\nHOWE\nHINTON\nHURLEY\nSPENCE\nZAMORA\nYANG\nMCNEIL\nSUAREZ\nCASE\nPETTY\nGOULD\nMCFARLAND\nSAMPSON\nCARVER\nBRAY\nROSARIO\nMACDONALD\nSTOUT\nHESTER\nMELENDEZ\nDILLON\nFARLEY\nHOPPER\nGALLOWAY\nPOTTS\nBERNARD\nJOYNER\nSTEIN\nAGUIRRE\nOSBORN\nMERCER\nBENDER\nFRANCO\nROWLAND\nSYKES\nBENJAMIN\nTRAVIS\nPICKETT\nCRANE\nSEARS\nMAYO\nDUNLAP\nHAYDEN\nWILDER\nMCKAY\nCOFFEY\nMCCARTY\nEWING\nCOOLEY\nVAUGHAN\nBONNER\nCOTTON\nHOLDER\nSTARK\nFERRELL\nCANTRELL\nFULTON\nLYNN\nLOTT\nCALDERON\nROSA\nPOLLARD\nHOOPER\nBURCH\nMULLEN\nFRY\nRIDDLE\nLEVY\nDAVID\nDUKE\nODONNELL\nGUY\nMICHAEL\nBRITT\nFREDERICK\nDAUGHERTY\nBERGER\nDILLARD\nALSTON\nJARVIS\nFRYE\nRIGGS\nCHANEY\nODOM\nDUFFY\nFITZPATRICK\nVALENZUELA\nMERRILL\nMAYER\nALFORD\nMCPHERSON\nACEVEDO\nDONOVAN\nBARRERA\nALBERT\nCOTE\nREILLY\nCOMPTON\nRAYMOND\nMOONEY\nMCGOWAN\nCRAFT\nCLEVELAND\nCLEMONS\nWYNN\nNIELSEN\nBAIRD\nSTANTON\nSNIDER\nROSALES\nBRIGHT\nWITT\nSTUART\nHAYS\nHOLDEN\nRUTLEDGE\nKINNEY\nCLEMENTS\nCASTANEDA\nSLATER\nHAHN\nEMERSON\nCONRAD\nBURKS\nDELANEY\nPATE\nLANCASTER\nSWEET\nJUSTICE\nTYSON\nSHARPE\nWHITFIELD\nTALLEY\nMACIAS\nIRWIN\nBURRIS\nRATLIFF\nMCCRAY\nMADDEN\nKAUFMAN\nBEACH\nGOFF\nCASH\nBOLTON\nMCFADDEN\nLEVINE\nGOOD\nBYERS\nKIRKLAND\nKIDD\nWORKMAN\nCARNEY\nDALE\nMCLEOD\nHOLCOMB\nENGLAND\nFINCH\nHEAD\nBURT\nHENDRIX\nSOSA\nHANEY\nFRANKS\nSARGENT\nNIEVES\nDOWNS\nRASMUSSEN\nBIRD\nHEWITT\nLINDSAY\nLE\nFOREMAN\nVALENCIA\nONEIL\nDELACRUZ\nVINSON\nDEJESUS\nHYDE\nFORBES\nGILLIAM\nGUTHRIE\nWOOTEN\nHUBER\nBARLOW\nBOYLE\nMCMAHON\nBUCKNER\nROCHA\nPUCKETT\nLANGLEY\nKNOWLES\nCOOKE\nVELAZQUEZ\nWHITLEY\nNOEL\nVANG\nCHEESE";
            LastNames = splitString.Split('\n');
            Logger.Info($"File at {lastNamesPath} does NOT exist. Falling back to biggie cheese last names...");
        }
        Maxes = [];
        if (z5tm.Instance.LastNames != null)
        {
            Logger.Info($"LastNames wasn't null! Adding {z5tm.Instance.LastNames.Length} to maxes.");
            Maxes.Add(z5tm.Instance.LastNames.Length);
        }

        if (z5tm.Instance.MascNames != null)
        {
            Logger.Info($"MascNames wasn't null! Adding {z5tm.Instance.MascNames.Length} to maxes.");
            Maxes.Add(z5tm.Instance.MascNames.Length);
        }

        if (z5tm.Instance.FemNames != null)
        {
            Logger.Info($"FemNames wasn't null! Adding {z5tm.Instance.FemNames.Length} to maxes.");
            Maxes.Add(z5tm.Instance.FemNames.Length);
        }
    }

    public void Deinitialize()
    {
        PlayerEvents.Hurt -= AdrenalineRush.Adrenaline; // hello !
        if (!Instance.Config.RPNameOnSpawn) return;
        PlayerEvents.ChangedRole -= RolePlayNameSetter.DoRoleplayNamingShit;
        ServerEvents.WaitingForPlayers -= RolePlayNameSetter.RoundStartingShit;
        // PlayerEvents.Death -= roleplaynamesetter.playerdead;
        // PlayerEvents.Dying -= roleplaynamesetter.SaveNamesOnDeath;
    }
}